In [1]:
import yfinance as yf
import statsmodels.api as sm
from datetime import datetime, timedelta
import numpy as np

In [2]:
import pandas as pd
pd.set_option('display.max_rows', None)

In [3]:
print(yf.__version__)

0.2.54

In [9]:
# stock = yf.Ticker("ADS.DE")
# benchmark = yf.Ticker("^GDAXI")
# stock = yf.Ticker("SRF.NS")
stock = yf.Ticker("SBIN.NS")
benchmark = yf.Ticker("^NSEI")

In [10]:
stock

yfinance.Ticker object <SBIN.NS>

In [25]:
[i['content']['title'] for i in stock.news]
# stock.news

["State Bank of India sees sector's personal loan woes easing on tighter credit rules",
 'State Bank of India (SBKFF) Q3 2025 Earnings Call Highlights: Robust Profit Growth Amidst ...',
 'State Bank of India aims to raise 50 billion rupees via perpetual bonds, sources say',
 'BPCL secures financial closure for Bina Refinery expansion project in India',
 'State Bank of India plans significant expansion of branch network',
 'State Bank of India (FRA:SID) Q2 2025 Earnings Call Highlights: Robust Profit Growth and ...',
 'How to invest in the Indian stock market',
 "India's SBI aims to sell its Yes Bank stake worth $2.2 billion by end-March, sources say",
 "State Bank of India's Dividend Analysis",
 "UPDATE 2-India's top court orders SBI bank to share political donors' names by Tuesday"]

In [26]:
stock.growth_estimates['stock']

KeyError: 'stock'

In [6]:
stock.growth_estimates

        stockTrend  indexTrend
period
0q         -0.1393      0.1434
+1q        -0.0513      0.0774
0y         -0.0234      0.1092
+1y         0.0466      0.1419
LTG            NaN      0.1030

In [7]:
end_date = datetime.now()
start_date = end_date - timedelta(days=30 * 6)

In [8]:
stock_hist = stock.history(start=start_date, end=end_date)

In [11]:
stock_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-26 00:00:00+05:30,818.000000,823.450012,813.799988,815.049988,8523795,0.0,0.0
2024-08-27 00:00:00+05:30,817.799988,819.450012,811.049988,815.900024,12833290,0.0,0.0
2024-08-28 00:00:00+05:30,814.750000,817.200012,806.500000,809.400024,10371300,0.0,0.0
2024-08-29 00:00:00+05:30,809.549988,816.000000,806.950012,814.500000,18247268,0.0,0.0
2024-08-30 00:00:00+05:30,817.150024,820.700012,814.349976,815.599976,8911426,0.0,0.0
2024-09-02 00:00:00+05:30,817.299988,825.400024,813.049988,822.150024,11813750,0.0,0.0
2024-09-03 00:00:00+05:30,822.150024,825.950012,816.400024,824.799988,10548350,0.0,0.0
2024-09-04 00:00:00+05:30,815.450012,818.650024,813.650024,816.500000,10789570,0.0,0.0
2024-09-05 00:00:00+05:30,818.349976,822.150024,814.400024,818.750000,8395074,0.0,0.0
2024-09-06 00:00:00+05:30,811.500000,812.900024,777.000000,782.500000,40220096,0.0,0.0
2024-09-09 00:00:00+05:30,785.000000,788.200012,771.000000,784.250000,21322103,0.0,0.0
2024-09-10 00:00:00+05:30,788.000000,788.799988,777.500000,782.650024,12824701,0.0,0.0
2024-09-11 00:00:00+05:30,780.049988,788.000000,765.400024,768.599976,20060665,0.0,0.0
2024-09-12 00:00:00+05:30,775.000000,789.900024,772.750000,787.750000,17578964,0.0,0.0
2024-09-13 00:00:00+05:30,791.000000,795.000000,785.099976,790.849976,12950936,0.0,0.0
2024-09-16 00:00:00+05:30,790.849976,795.000000,784.400024,785.549988,9553736,0.0,0.0
2024-09-17 00:00:00+05:30,785.599976,787.500000,780.549988,782.900024,10665630,0.0,0.0
2024-09-18 00:00:00+05:30,783.799988,794.750000,782.000000,792.750000,18324412,0.0,0.0
2024-09-19 00:00:00+05:30,795.049988,801.349976,784.049988,789.950012,10645478,0.0,0.0
2024-09-20 00:00:00+05:30,794.849976,794.849976,779.500000,781.700012,21372244,0.0,0.0
2024-09-23 00:00:00+05:30,786.000000,805.000000,784.500000,801.849976,17309545,0.0,0.0
2024-09-24 00:00:00+05:30,799.250000,804.250000,796.500000,798.250000,15180653,0.0,0.0
2024-09-25 00:00:00+05:30,797.900024,798.000000,788.700012,793.099976,18465571,0.0,0.0
2024-09-26 00:00:00+05:30,796.000000,803.000000,791.599976,801.849976,23198842,0.0,0.0
2024-09-27 00:00:00+05:30,801.849976,808.000000,798.450012,802.650024,15193681,0.0,0.0
2024-09-30 00:00:00+05:30,801.900024,802.599976,786.450012,787.900024,15484573,0.0,0.0
2024-10-01 00:00:00+05:30,788.000000,800.349976,788.000000,796.950012,13280535,0.0,0.0
2024-10-03 00:00:00+05:30,789.900024,804.000000,784.299988,794.099976,15944135,0.0,0.0
2024-10-04 00:00:00+05:30,792.000000,809.849976,785.250000,796.650024,20097454,0.0,0.0
2024-10-07 00:00:00+05:30,800.000000,804.000000,765.400024,770.650024,24267990,0.0,0.0
2024-10-08 00:00:00+05:30,772.250000,784.400024,772.250000,781.450012,8560960,0.0,0.0
2024-10-09 00:00:00+05:30,786.700012,804.349976,782.049988,797.400024,18758697,0.0,0.0
2024-10-10 00:00:00+05:30,799.000000,804.450012,795.000000,797.099976,10241015,0.0,0.0
2024-10-11 00:00:00+05:30,797.200012,802.700012,793.000000,799.750000,14322720,0.0,0.0
2024-10-14 00:00:00+05:30,802.000000,809.250000,800.799988,805.150024,8967564,0.0,0.0
2024-10-15 00:00:00+05:30,805.500000,807.500000,801.599976,804.650024,6252104,0.0,0.0
2024-10-16 00:00:00+05:30,802.799988,809.000000,802.049988,805.450012,6494240,0.0,0.0
2024-10-17 00:00:00+05:30,809.500000,819.500000,806.000000,811.049988,18580553,0.0,0.0
2024-10-18 00:00:00+05:30,811.099976,822.599976,802.900024,820.400024,11704698,0.0,0.0
2024-10-21 00:00:00+05:30,824.700012,826.450012,809.000000,813.950012,10359618,0.0,0.0
2024-10-22 00:00:00+05:30,814.000000,816.849976,787.500000,790.400024,16645356,0.0,0.0
2024-10-23 00:00:00+05:30,790.000000,792.599976,779.799988,786.000000,13866198,0.0,0.0
2024-10-24 00:00:00+05:30,786.049988,797.000000,784.650024,794.549988,5607500,0.0,0.0
2024-10-25 00:00:00+05:30,798.000000,800.750000,772.000000,780.950012,9717125,0.0,0.0
2024-10-28 00:00:00+05:30,783.799988,803.950012,783.549988,792.049988,13757251,0.0,0.0
2024-10-29 00:00:00+05:30,796.000000,834.849976,790.500000,832.700012,28274791,0.0,0.0
2024-10-30 00:00:00+05:30,828.000000,833.000000,821.049988,822.450012,15977682,0.0,0.0
2024-10-31 00:00:00+05:30,820.000000,828.000000,813.549988,820.200012,13402324,0.0,0.0
2024-11-01 00:00:00+05:30,822.400024,825.599976,818.900024,821.200012,1637141,0.0,0.0
2024-11-04 00:00:00+05:30,822.700012,837.500000,807.099976,829.849976,14498161,0.0,0.0
2024-11-05 00:00:00+05:30,829.849976,851.400024,826.250000,849.200012,26254561,0.0,0.0
2024-11-06 00:00:00+05:30,849.200012,861.400024,846.200012,854.799988,15002433,0.0,0.0
2024-11-07 00:00:00+05:30,861.000000,862.400024,846.700012,859.599976,15283847,0.0,0.0
2024-11-08 00:00:00+05:30,859.599976,863.500000,834.200012,843.150024,26139105,0.0,0.0
2024-11-11 00:00:00+05:30,846.000000,854.000000,842.000000,847.650024,12621337,0.0,0.0
2024-11-12 00:00:00+05:30,852.500000,853.400024,824.299988,826.700012,11350729,0.0,0.0
2024-11-13 00:00:00+05:30,823.349976,831.750000,804.650024,808.650024,13756706,0.0,0.0
2024-11-14 00:00:00+05:30,808.650024,818.000000,801.049988,804.250000,9461484,0.0,0.0
2024-11-18 00:00:00+05:30,811.000000,816.700012,799.250000,814.299988,9322451,0.0,0.0
2024-11-19 00:00:00+05:30,819.000000,820.299988,800.099976,803.000000,13677029,0.0,0.0
2024-11-21 00:00:00+05:30,798.500000,798.500000,761.549988,780.750000,29486577,0.0,0.0
2024-11-22 00:00:00+05:30,786.000000,819.950012,784.049988,816.049988,20665405,0.0,0.0
2024-11-25 00:00:00+05:30,827.000000,849.599976,825.650024,844.450012,23434605,0.0,0.0
2024-11-26 00:00:00+05:30,844.000000,846.700012,835.549988,839.400024,8893744,0.0,0.0
2024-11-27 00:00:00+05:30,838.500000,842.500000,832.099976,834.099976,8375108,0.0,0.0
2024-11-28 00:00:00+05:30,834.099976,845.799988,830.500000,838.849976,13505677,0.0,0.0
2024-11-29 00:00:00+05:30,841.099976,844.049988,831.549988,838.950012,10822949,0.0,0.0
2024-12-02 00:00:00+05:30,838.950012,842.000000,832.700012,836.400024,6651119,0.0,0.0
2024-12-03 00:00:00+05:30,838.000000,856.599976,836.900024,853.950012,12186182,0.0,0.0
2024-12-04 00:00:00+05:30,853.950012,864.000000,850.299988,859.700012,10749716,0.0,0.0
2024-12-05 00:00:00+05:30,860.000000,871.450012,855.599976,865.450012,14716036,0.0,0.0
2024-12-06 00:00:00+05:30,865.250000,875.450012,857.000000,863.650024,14520568,0.0,0.0
2024-12-09 00:00:00+05:30,859.000000,866.849976,856.950012,858.049988,9630346,0.0,0.0
2024-12-10 00:00:00+05:30,861.799988,868.950012,858.049988,867.500000,7379849,0.0,0.0
2024-12-11 00:00:00+05:30,867.500000,869.849976,860.950012,861.599976,7006973,0.0,0.0
2024-12-12 00:00:00+05:30,861.500000,864.299988,851.150024,853.700012,8845103,0.0,0.0
2024-12-13 00:00:00+05:30,852.599976,862.900024,835.000000,861.549988,9379370,0.0,0.0
2024-12-16 00:00:00+05:30,859.799988,866.400024,857.799988,860.950012,6432713,0.0,0.0
2024-12-17 00:00:00+05:30,858.549988,862.599976,847.049988,850.549988,8791216,0.0,0.0
2024-12-18 00:00:00+05:30,851.000000,852.000000,837.000000,838.150024,8295338,0.0,0.0
2024-12-19 00:00:00+05:30,824.599976,838.000000,820.200012,832.799988,9453398,0.0,0.0
2024-12-20 00:00:00+05:30,834.900024,836.000000,810.000000,812.000000,10244198,0.0,0.0
2024-12-23 00:00:00+05:30,817.299988,824.000000,812.200012,821.150024,4933200,0.0,0.0
2024-12-24 00:00:00+05:30,824.250000,826.200012,809.200012,812.049988,10602771,0.0,0.0
2024-12-26 00:00:00+05:30,813.000000,822.849976,808.000000,812.450012,8318714,0.0,0.0
2024-12-27 00:00:00+05:30,816.299988,818.299988,797.200012,799.650024,10649800,0.0,0.0
2024-12-30 00:00:00+05:30,802.000000,807.950012,785.000000,788.299988,21515438,0.0,0.0
2024-12-31 00:00:00+05:30,786.950012,799.200012,786.000000,794.950012,9086044,0.0,0.0
2025-01-01 00:00:00+05:30,795.549988,798.650024,789.500000,793.200012,7273098,0.0,0.0
2025-01-02 00:00:00+05:30,795.000000,802.400024,787.000000,801.200012,11398319,0.0,0.0
2025-01-03 00:00:00+05:30,801.200012,809.500000,792.150024,793.400024,13336514,0.0,0.0
2025-01-06 00:00:00+05:30,797.400024,797.599976,773.150024,776.400024,11419367,0.0,0.0
2025-01-07 00:00:00+05:30,779.849976,783.849976,774.849976,778.750000,9669152,0.0,0.0
2025-01-08 00:00:00+05:30,780.900024,783.950012,760.099976,771.150024,15641490,0.0,0.0
2025-01-09 00:00:00+05:30,771.150024,771.349976,726.250000,760.450012,15351029,0.0,0.0
2025-01-10 00:00:00+05:30,760.349976,763.400024,742.049988,743.250000,11779296,0.0,0.0
2025-01-13 00:00:00+05:30,741.500000,743.950012,722.500000,729.500000,10414733,0.0,0.0
2025-01-14 00:00:00+05:30,732.950012,757.000000,732.950012,748.150024,11960975,0.0,0.0
2025-01-15 00:00:00+05:30,753.150024,758.900024,750.000000,753.700012,7792299,0.0,0.0
2025-01-16 00:00:00+05:30,760.400024,776.700012,760.400024,766.299988,11816079,0.0,0.0
2025-01-17 00:00:00+05:30,766.299988,767.950012,759.400024,764.099976,5766573,0.0,0.0
2025-01-20 00:00:00+05:30,769.000000,785.000000,767.849976,779.250000,9198929,0.0,0.0
2025-01-21 00:00:00+05:30,784.799988,784.900024,756.049988,759.049988,13751780,0.0,0.0
2025-01-22 00:00:00+05:30,762.000000,763.000000,738.000000,753.450012,9908339,0.0,0.0
2025-01-23 00:00:00+05:30,750.000000,755.650024,743.099976,745.900024,10986405,0.0,0.0
2025-01-24 00:00:00+05:30,749.900024,753.700012,739.000000,744.150024,10579213,0.0,0.0
2025-01-27 00:00:00+05:30,740.000000,755.349976,735.900024,749.200012,11433353,0.0,0.0
2025-01-28 00:00:00+05:30,757.000000,759.750000,745.400024,752.400024,14140860,0.0,0.0
2025-01-29 00:00:00+05:30,753.000000,760.799988,749.799988,758.450012,9251973,0.0,0.0
2025-01-30 00:00:00+05:30,758.549988,765.000000,754.750000,762.599976,11085824,0.0,0.0
2025-01-31 00:00:00+05:30,764.900024,777.549988,759.500000,772.900024,10083763,0.0,0.0
2025-02-01 00:00:00+05:30,774.799988,778.750000,752.150024,766.000000,9363077,0.0,0.0
2025-02-03 00:00:00+05:30,762.799988,762.799988,753.150024,760.950012,7862190,0.0,0.0
2025-02-04 00:00:00+05:30,767.000000,781.250000,765.650024,779.200012,12020807,0.0,0.0
2025-02-05 00:00:00+05:30,780.000000,782.000000,765.000000,766.049988,13419162,0.0,0.0
2025-02-06 00:00:00+05:30,769.000000,770.849976,750.049988,752.250000,32745391,0.0,0.0
2025-02-07 00:00:00+05:30,759.799988,759.900024,731.750000,737.200012,37240692,0.0,0.0
2025-02-10 00:00:00+05:30,740.000000,743.900024,733.400024,736.799988,12667049,0.0,0.0
2025-02-11 00:00:00+05:30,737.450012,740.150024,726.549988,731.099976,13017060,0.0,0.0
2025-02-12 00:00:00+05:30,733.150024,738.700012,717.150024,733.150024,12697743,0.0,0.0
2025-02-13 00:00:00+05:30,734.400024,737.500000,726.150024,727.650024,12370571,0.0,0.0
2025-02-14 00:00:00+05:30,730.950012,732.900024,716.200012,722.150024,10417539,0.0,0.0
2025-02-17 00:00:00+05:30,719.049988,728.750000,711.549988,727.700012,9093600,0.0,0.0
2025-02-18 00:00:00+05:30,727.700012,728.250000,717.349976,725.799988,8562003,0.0,0.0
2025-02-19 00:00:00+05:30,722.049988,734.849976,722.049988,727.299988,6766606,0.0,0.0
2025-02-20 00:00:00+05:30,724.900024,731.500000,723.349976,729.700012,7418994,0.0,0.0

In [33]:
stock_hist.to_json()

'{"Open":{"1713736800000":226.1106323162,"1713823200000":224.3160962352,"1713909600000":229.3009008449,"1713996000000":226.9082024677,"1714082400000":227.4066887541,"1714341600000":230.3975683374,"1714428000000":232.1920806354,"1714600800000":227.3069793156,"1714687200000":225.4127636533,"1714946400000":224.017008697,"1715032800000":225.2133643788,"1715119200000":222.1227911284,"1715205600000":220.3282647231,"1715292000000":224.3161083994,"1715551200000":223.3191479176,"1715637600000":224.615197114,"1715724000000":226.5094158179,"1715810400000":231.0954314948,"1715896800000":228.6999969482,"1716156000000":228.8999938965,"1716242400000":227.1999969482,"1716328800000":227.0,"1716415200000":225.1000061035,"1716501600000":222.1000061035,"1716760800000":223.6999969482,"1716847200000":223.0,"1716933600000":221.5,"1717020000000":228.0,"1717106400000":230.8999938965,"1717365600000":234.0,"1717452000000":232.5,"1717538400000":232.6999969482,"1717624800000":233.6000061035,"1717711200000":230.8000030518,"1717970400000":230.0,"1718056800000":230.0,"1718143200000":227.0,"1718229600000":229.8000030518,"1718316000000":227.3000030518,"1718575200000":224.8999938965,"1718661600000":221.1999969482,"1718748000000":215.8999938965,"1718834400000":215.5,"1718920800000":221.6999969482,"1719180000000":217.8999938965,"1719266400000":220.8000030518,"1719352800000":219.8999938965,"1719439200000":220.0,"1719525600000":223.3999938965,"1719784800000":224.3999938965,"1719871200000":219.3999938965,"1719957600000":216.5,"1720044000000":218.1999969482,"1720130400000":219.8999938965,"1720389600000":220.3000030518,"1720476000000":218.6000061035,"1720562400000":217.0,"1720648800000":222.8000030518,"1720735200000":226.5,"1720994400000":230.6999969482,"1721080800000":230.0,"1721167200000":237.0,"1721253600000":234.8999938965,"1721340000000":229.8000030518,"1721599200000":228.3000030518,"1721685600000":228.5,"1721772000000":226.6000061035,"1721858400000":230.6999969482,"1721944800000":228.5,"1722204000000":233.8000030518,"1722290400000":236.0,"1722376800000":235.0,"1722463200000":230.0,"1722549600000":223.5,"1722808800000":214.0,"1722895200000":214.3000030518,"1722981600000":213.0,"1723068000000":214.6999969482,"1723154400000":215.1000061035,"1723413600000":215.5,"1723500000000":213.1999969482,"1723586400000":214.6000061035,"1723672800000":217.3000030518,"1723759200000":219.3999938965,"1724018400000":217.1999969482,"1724104800000":217.6999969482,"1724191200000":213.6000061035,"1724277600000":216.6999969482,"1724364000000":217.8000030518,"1724623200000":218.6999969482,"1724709600000":220.0,"1724796000000":223.6999969482,"1724882400000":227.1000061035,"1724968800000":230.8999938965,"1725228000000":231.6999969482,"1725314400000":230.3999938965,"1725400800000":227.3000030518,"1725487200000":223.0,"1725573600000":221.3000030518,"1725832800000":215.3000030518,"1725919200000":214.0,"1726005600000":210.1000061035,"1726092000000":215.3000030518,"1726178400000":219.1999969482,"1726437600000":218.0,"1726524000000":219.0,"1726610400000":220.3999938965,"1726696800000":223.8000030518,"1726783200000":221.1999969482,"1727042400000":217.8999938965,"1727128800000":222.3000030518,"1727215200000":220.0,"1727301600000":227.6999969482,"1727388000000":235.6000061035,"1727647200000":239.0,"1727733600000":238.3000030518,"1727820000000":231.1999969482,"1727906400000":236.6999969482,"1727992800000":235.8999938965,"1728252000000":239.8000030518,"1728338400000":233.6999969482,"1728424800000":235.6999969482,"1728511200000":237.1999969482,"1728597600000":232.5,"1728856800000":235.0,"1728943200000":237.8999938965,"1729029600000":230.0,"1729116000000":224.0,"1729202400000":224.0},"High":{"1713736800000":226.8085015863,"1713823200000":227.2072753906,"1713909600000":230.4972503285,"1713996000000":227.3069805592,"1714082400000":230.1981658936,"1714341600000":233.1890454549,"1714428000000":232.1920806354,"1714600800000":227.3069793156,"1714687200000":226.2103198428,"1714946400000":225.3130603165,"1715032800000":226.609118166,"1715119200000":223.5185296724,"1715205600000":223.02005496,"1715292000000":224.8145886403,"1715551200000":225.8115491221,"1715637600000":227.0078961589,"1715724000000":231.39453125,"1715810400000":232.3914831006,"1715896800000":230.0,"1716156000000":229.1000061035,"1716242400000":228.3000030518,"1716328800000":228.8000030518,"1716415200000":226.1000061035,"1716501600000":223.8999938965,"1716760800000":223.6999969482,"1716847200000":223.1999969482,"1716933600000":228.1999969482,"1717020000000":232.0,"1717106400000":231.6999969482,"1717365600000":236.3000030518,"1717452000000":234.3000030518,"1717538400000":234.1000061035,"1717624800000":234.1000061035,"1717711200000":231.0,"1717970400000":231.3000030518,"1718056800000":230.3999938965,"1718143200000":231.0,"1718229600000":230.3000030518,"1718316000000":227.8999938965,"1718575200000":225.0,"1718661600000":222.1999969482,"1718748000000":216.1000061035,"1718834400000":221.3000030518,"1718920800000":221.6999969482,"1719180000000":220.8999938965,"1719266400000":220.8000030518,"1719352800000":222.8999938965,"1719439200000":223.5,"1719525600000":226.3999938965,"1719784800000":225.3000030518,"1719871200000":220.1000061035,"1719957600000":220.3999938965,"1720044000000":219.5,"1720130400000":223.1000061035,"1720389600000":222.6999969482,"1720476000000":219.6000061035,"1720562400000":222.1000061035,"1720648800000":226.0,"1720735200000":231.1999969482,"1720994400000":234.6999969482,"1721080800000":230.3000030518,"1721167200000":240.3999938965,"1721253600000":235.3999938965,"1721340000000":231.3999938965,"1721599200000":229.3999938965,"1721685600000":230.8999938965,"1721772000000":232.6000061035,"1721858400000":232.0,"1721944800000":233.0,"1722204000000":237.1999969482,"1722290400000":237.1000061035,"1722376800000":242.0,"1722463200000":231.8000030518,"1722549600000":225.1999969482,"1722808800000":215.3999938965,"1722895200000":216.0,"1722981600000":217.5,"1723068000000":216.1999969482,"1723154400000":216.1000061035,"1723413600000":216.8000030518,"1723500000000":213.6999969482,"1723586400000":218.3000030518,"1723672800000":220.3000030518,"1723759200000":219.5,"1724018400000":218.1000061035,"1724104800000":217.8999938965,"1724191200000":217.8000030518,"1724277600000":218.1999969482,"1724364000000":219.3999938965,"1724623200000":219.6000061035,"1724709600000":223.6999969482,"1724796000000":229.8000030518,"1724882400000":231.6999969482,"1724968800000":236.5,"1725228000000":231.6999969482,"1725314400000":231.5,"1725400800000":229.6000061035,"1725487200000":224.0,"1725573600000":222.8999938965,"1725832800000":215.6999969482,"1725919200000":215.1999969482,"1726005600000":213.8000030518,"1726092000000":220.1000061035,"1726178400000":219.8999938965,"1726437600000":220.6000061035,"1726524000000":222.5,"1726610400000":222.0,"1726696800000":227.5,"1726783200000":221.8000030518,"1727042400000":220.3000030518,"1727128800000":223.0,"1727215200000":224.1000061035,"1727301600000":236.1999969482,"1727388000000":240.3000030518,"1727647200000":243.8999938965,"1727733600000":239.6000061035,"1727820000000":240.6000061035,"1727906400000":237.3000030518,"1727992800000":239.5,"1728252000000":239.8000030518,"1728338400000":238.0,"1728424800000":238.3000030518,"1728511200000":237.1999969482,"1728597600000":233.6000061035,"1728856800000":238.8999938965,"1728943200000":240.8000030518,"1729029600000":235.1000061035,"1729116000000":227.3000030518,"1729202400000":231.3999938965},"Low":{"1713736800000":221.9234014832,"1713823200000":223.4188379352,"1713909600000":226.1106304843,"1713996000000":223.8176190155,"1714082400000":224.1167161684,"1714341600000":229.8990881076,"1714428000000":224.216397107,"1714600800000":221.7239947913,"1714687200000":221.8236999512,"1714946400000":223.518528475,"1715032800000":220.1288751027,"1715119200000":220.2285571475,"1715205600000":219.0322130646,"1715292000000":222.0230962489,"1715551200000":223.1197588638,"1715637600000":223.6182366432,"1715724000000":226.2103246343,"1715810400000":226.4097205005,"1715896800000":228.6999969482,"1716156000000":226.8999938965,"1716242400000":224.8000030518,"1716328800000":224.6000061035,"1716415200000":220.8999938965,"1716501600000":220.8999938965,"1716760800000":222.0,"1716847200000":220.5,"1716933600000":221.3000030518,"1717020000000":227.6999969482,"1717106400000":229.6000061035,"1717365600000":232.6999969482,"1717452000000":229.8000030518,"1717538400000":230.1000061035,"1717624800000":230.5,"1717711200000":228.6999969482,"1717970400000":228.6999969482,"1718056800000":224.3999938965,"1718143200000":224.3999938965,"1718229600000":225.6000061035,"1718316000000":222.3000030518,"1718575200000":215.1000061035,"1718661600000":214.8999938965,"1718748000000":214.3000030518,"1718834400000":214.3000030518,"1718920800000":216.5,"1719180000000":216.3000030518,"1719266400000":217.6999969482,"1719352800000":218.5,"1719439200000":219.5,"1719525600000":220.3999938965,"1719784800000":219.5,"1719871200000":211.3000030518,"1719957600000":215.1999969482,"1720044000000":216.6999969482,"1720130400000":218.8000030518,"1720389600000":218.6999969482,"1720476000000":216.1000061035,"1720562400000":216.3000030518,"1720648800000":221.3000030518,"1720735200000":226.3000030518,"1720994400000":229.5,"1721080800000":225.3000030518,"1721167200000":232.8000030518,"1721253600000":230.1999969482,"1721340000000":226.6999969482,"1721599200000":226.6999969482,"1721685600000":227.1000061035,"1721772000000":224.6999969482,"1721858400000":228.8000030518,"1721944800000":227.8000030518,"1722204000000":231.6999969482,"1722290400000":232.6000061035,"1722376800000":227.3999938965,"1722463200000":224.8999938965,"1722549600000":218.1999969482,"1722808800000":209.6999969482,"1722895200000":208.6999969482,"1722981600000":210.6000061035,"1723068000000":210.8000030518,"1723154400000":212.8999938965,"1723413600000":211.3000030518,"1723500000000":208.8999938965,"1723586400000":214.1000061035,"1723672800000":216.1000061035,"1723759200000":216.6999969482,"1724018400000":215.8000030518,"1724104800000":213.8000030518,"1724191200000":213.6000061035,"1724277600000":216.3999938965,"1724364000000":215.8999938965,"1724623200000":218.0,"1724709600000":219.1000061035,"1724796000000":223.3999938965,"1724882400000":226.3999938965,"1724968800000":229.6999969482,"1725228000000":228.8999938965,"1725314400000":228.6999969482,"1725400800000":222.3999938965,"1725487200000":219.8999938965,"1725573600000":217.0,"1725832800000":207.8000030518,"1725919200000":208.1999969482,"1726005600000":209.6000061035,"1726092000000":214.3000030518,"1726178400000":218.1000061035,"1726437600000":217.1999969482,"1726524000000":218.6000061035,"1726610400000":219.3000030518,"1726696800000":222.1000061035,"1726783200000":217.1000061035,"1727042400000":216.8000030518,"1727128800000":220.1999969482,"1727215200000":219.1999969482,"1727301600000":227.5,"1727388000000":234.8000030518,"1727647200000":236.8000030518,"1727733600000":232.6000061035,"1727820000000":230.5,"1727906400000":232.8999938965,"1727992800000":235.1000061035,"1728252000000":236.6999969482,"1728338400000":232.3000030518,"1728424800000":233.8000030518,"1728511200000":230.8999938965,"1728597600000":231.5,"1728856800000":234.1999969482,"1728943200000":236.6999969482,"1729029600000":224.1999969482,"1729116000000":222.6000061035,"1729202400000":227.0},"Close":{"1713736800000":223.1197509766,"1713823200000":227.2072753906,"1713909600000":227.0078887939,"1713996000000":225.7118377686,"1714082400000":230.1981658936,"1714341600000":231.5939178467,"1714428000000":225.7118377686,"1714600800000":223.3191375732,"1714687200000":224.3161010742,"1714946400000":224.415802002,"1715032800000":221.4249267578,"1715119200000":221.8236999512,"1715205600000":222.6212768555,"1715292000000":223.7179260254,"1715551200000":223.7179260254,"1715637600000":226.4097290039,"1715724000000":231.39453125,"1715810400000":229.5999908447,"1715896800000":228.8999938965,"1716156000000":227.6999969482,"1716242400000":228.0,"1716328800000":225.3999938965,"1716415200000":222.8999938965,"1716501600000":223.8999938965,"1716760800000":222.6999969482,"1716847200000":222.3000030518,"1716933600000":227.1000061035,"1717020000000":231.5,"1717106400000":231.5,"1717365600000":232.8999938965,"1717452000000":232.3999938965,"1717538400000":231.6999969482,"1717624800000":231.1999969482,"1717711200000":231.0,"1717970400000":229.6999969482,"1718056800000":225.8000030518,"1718143200000":230.3999938965,"1718229600000":227.5,"1718316000000":224.8999938965,"1718575200000":219.1000061035,"1718661600000":216.0,"1718748000000":215.0,"1718834400000":221.1999969482,"1718920800000":217.8000030518,"1719180000000":220.1000061035,"1719266400000":217.8999938965,"1719352800000":222.1999969482,"1719439200000":222.6000061035,"1719525600000":223.0,"1719784800000":219.5,"1719871200000":216.0,"1719957600000":218.1000061035,"1720044000000":219.5,"1720130400000":220.3000030518,"1720389600000":218.8000030518,"1720476000000":216.1000061035,"1720562400000":221.3000030518,"1720648800000":225.8000030518,"1720735200000":231.1999969482,"1720994400000":231.3999938965,"1721080800000":228.6999969482,"1721167200000":233.5,"1721253600000":232.8000030518,"1721340000000":227.1000061035,"1721599200000":228.6999969482,"1721685600000":230.3999938965,"1721772000000":232.6000061035,"1721858400000":229.1000061035,"1721944800000":233.0,"1722204000000":235.8000030518,"1722290400000":236.6000061035,"1722376800000":231.3000030518,"1722463200000":225.5,"1722549600000":218.6999969482,"1722808800000":214.8999938965,"1722895200000":213.1999969482,"1722981600000":216.6999969482,"1723068000000":215.5,"1723154400000":214.6000061035,"1723413600000":212.3999938965,"1723500000000":213.3000030518,"1723586400000":217.1999969482,"1723672800000":218.3999938965,"1723759200000":217.0,"1724018400000":217.6000061035,"1724104800000":214.1000061035,"1724191200000":217.3999938965,"1724277600000":217.5,"1724364000000":219.1999969482,"1724623200000":218.8999938965,"1724709600000":223.6999969482,"1724796000000":227.0,"1724882400000":231.6000061035,"1724968800000":232.0,"1725228000000":230.0,"1725314400000":230.0,"1725400800000":224.5,"1725487200000":222.0,"1725573600000":220.6999969482,"1725832800000":214.0,"1725919200000":209.1000061035,"1726005600000":212.8000030518,"1726092000000":218.5,"1726178400000":218.5,"1726437600000":219.3000030518,"1726524000000":221.1000061035,"1726610400000":220.1999969482,"1726696800000":227.1000061035,"1726783200000":217.8000030518,"1727042400000":218.5,"1727128800000":220.5,"1727215200000":222.5,"1727301600000":233.8000030518,"1727388000000":240.3000030518,"1727647200000":237.8999938965,"1727733600000":232.8000030518,"1727820000000":237.1999969482,"1727906400000":236.5,"1727992800000":238.1999969482,"1728252000000":238.3000030518,"1728338400000":235.0,"1728424800000":235.8999938965,"1728511200000":232.6999969482,"1728597600000":233.6000061035,"1728856800000":236.8000030518,"1728943200000":239.6999969482,"1729029600000":224.6999969482,"1729116000000":225.3000030518,"1729202400000":227.8999938965},"Volume":{"1713736800000":440247,"1713823200000":429712,"1713909600000":482904,"1713996000000":348040,"1714082400000":370777,"1714341600000":386905,"1714428000000":536674,"1714600800000":497954,"1714687200000":420986,"1714946400000":240835,"1715032800000":427458,"1715119200000":391297,"1715205600000":341375,"1715292000000":390013,"1715551200000":234383,"1715637600000":280605,"1715724000000":471027,"1715810400000":440065,"1715896800000":396821,"1716156000000":208244,"1716242400000":420738,"1716328800000":282772,"1716415200000":554331,"1716501600000":372335,"1716760800000":167826,"1716847200000":386779,"1716933600000":601744,"1717020000000":438957,"1717106400000":754394,"1717365600000":343377,"1717452000000":238332,"1717538400000":289657,"1717624800000":280535,"1717711200000":338479,"1717970400000":303861,"1718056800000":366456,"1718143200000":352295,"1718229600000":431958,"1718316000000":513627,"1718575200000":616003,"1718661600000":456994,"1718748000000":203351,"1718834400000":456250,"1718920800000":845215,"1719180000000":392140,"1719266400000":328573,"1719352800000":443187,"1719439200000":431701,"1719525600000":893100,"1719784800000":495056,"1719871200000":451962,"1719957600000":348200,"1720044000000":196939,"1720130400000":295332,"1720389600000":272629,"1720476000000":242949,"1720562400000":451996,"1720648800000":371141,"1720735200000":421911,"1720994400000":496283,"1721080800000":368867,"1721167200000":915133,"1721253600000":433937,"1721340000000":471432,"1721599200000":338049,"1721685600000":248657,"1721772000000":373108,"1721858400000":318572,"1721944800000":345891,"1722204000000":530967,"1722290400000":436335,"1722376800000":1063820,"1722463200000":463001,"1722549600000":531871,"1722808800000":404843,"1722895200000":462842,"1722981600000":398434,"1723068000000":289785,"1723154400000":266147,"1723413600000":206714,"1723500000000":292101,"1723586400000":288491,"1723672800000":321406,"1723759200000":325628,"1724018400000":242386,"1724104800000":268193,"1724191200000":311709,"1724277600000":189030,"1724364000000":184926,"1724623200000":125673,"1724709600000":329311,"1724796000000":456171,"1724882400000":313245,"1724968800000":621404,"1725228000000":181709,"1725314400000":168526,"1725400800000":343327,"1725487200000":261795,"1725573600000":356991,"1725832800000":574068,"1725919200000":391410,"1726005600000":280574,"1726092000000":413837,"1726178400000":294596,"1726437600000":214071,"1726524000000":270742,"1726610400000":233820,"1726696800000":341822,"1726783200000":1052730,"1727042400000":260562,"1727128800000":334776,"1727215200000":289319,"1727301600000":556805,"1727388000000":459038,"1727647200000":481607,"1727733600000":500205,"1727820000000":491737,"1727906400000":254620,"1727992800000":329243,"1728252000000":362869,"1728338400000":357404,"1728424800000":483221,"1728511200000":396881,"1728597600000":360272,"1728856800000":299142,"1728943200000":406568,"1729029600000":989714,"1729116000000":533117,"1729202400000":414595},"Dividends":{"1713736800000":0.0,"1713823200000":0.0,"1713909600000":0.0,"1713996000000":0.0,"1714082400000":0.0,"1714341600000":0.0,"1714428000000":0.0,"1714600800000":0.0,"1714687200000":0.0,"1714946400000":0.0,"1715032800000":0.0,"1715119200000":0.0,"1715205600000":0.0,"1715292000000":0.0,"1715551200000":0.0,"1715637600000":0.0,"1715724000000":0.0,"1715810400000":0.0,"1715896800000":0.7,"1716156000000":0.0,"1716242400000":0.0,"1716328800000":0.0,"1716415200000":0.0,"1716501600000":0.0,"1716760800000":0.0,"1716847200000":0.0,"1716933600000":0.0,"1717020000000":0.0,"1717106400000":0.0,"1717365600000":0.0,"1717452000000":0.0,"1717538400000":0.0,"1717624800000":0.0,"1717711200000":0.0,"1717970400000":0.0,"1718056800000":0.0,"1718143200000":0.0,"1718229600000":0.0,"1718316000000":0.0,"1718575200000":0.0,"1718661600000":0.0,"1718748000000":0.0,"1718834400000":0.0,"1718920800000":0.0,"1719180000000":0.0,"1719266400000":0.0,"1719352800000":0.0,"1719439200000":0.0,"1719525600000":0.0,"1719784800000":0.0,"1719871200000":0.0,"1719957600000":0.0,"1720044000000":0.0,"1720130400000":0.0,"1720389600000":0.0,"1720476000000":0.0,"1720562400000":0.0,"1720648800000":0.0,"1720735200000":0.0,"1720994400000":0.0,"1721080800000":0.0,"1721167200000":0.0,"1721253600000":0.0,"1721340000000":0.0,"1721599200000":0.0,"1721685600000":0.0,"1721772000000":0.0,"1721858400000":0.0,"1721944800000":0.0,"1722204000000":0.0,"1722290400000":0.0,"1722376800000":0.0,"1722463200000":0.0,"1722549600000":0.0,"1722808800000":0.0,"1722895200000":0.0,"1722981600000":0.0,"1723068000000":0.0,"1723154400000":0.0,"1723413600000":0.0,"1723500000000":0.0,"1723586400000":0.0,"1723672800000":0.0,"1723759200000":0.0,"1724018400000":0.0,"1724104800000":0.0,"1724191200000":0.0,"1724277600000":0.0,"1724364000000":0.0,"1724623200000":0.0,"1724709600000":0.0,"1724796000000":0.0,"1724882400000":0.0,"1724968800000":0.0,"1725228000000":0.0,"1725314400000":0.0,"172540080

In [12]:
benchmark_hist = benchmark.history(start=start_date, end=end_date)

In [13]:
benchmark_hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-26 00:00:00+05:30,24906.099609,25043.800781,24874.699219,25010.599609,210300,0.0,0.0
2024-08-27 00:00:00+05:30,25024.800781,25073.099609,24973.650391,25017.750000,223300,0.0,0.0
2024-08-28 00:00:00+05:30,25030.800781,25129.599609,24964.650391,25052.349609,220400,0.0,0.0
2024-08-29 00:00:00+05:30,25035.300781,25192.900391,24998.500000,25151.949219,354000,0.0,0.0
2024-08-30 00:00:00+05:30,25249.699219,25268.349609,25199.400391,25235.900391,638200,0.0,0.0
2024-09-02 00:00:00+05:30,25333.599609,25333.650391,25235.500000,25278.699219,222800,0.0,0.0
2024-09-03 00:00:00+05:30,25313.400391,25321.699219,25235.800781,25279.849609,212100,0.0,0.0
2024-09-04 00:00:00+05:30,25089.949219,25216.000000,25083.800781,25198.699219,253800,0.0,0.0
2024-09-05 00:00:00+05:30,25250.500000,25275.449219,25127.750000,25145.099609,222200,0.0,0.0
2024-09-06 00:00:00+05:30,25093.699219,25168.750000,24801.300781,24852.150391,311700,0.0,0.0
2024-09-09 00:00:00+05:30,24823.400391,24957.500000,24753.150391,24936.400391,254400,0.0,0.0
2024-09-10 00:00:00+05:30,24999.400391,25130.500000,24896.800781,25041.099609,251300,0.0,0.0
2024-09-11 00:00:00+05:30,25034.000000,25113.699219,24885.150391,24918.449219,279200,0.0,0.0
2024-09-12 00:00:00+05:30,25059.650391,25433.349609,24941.449219,25388.900391,380100,0.0,0.0
2024-09-13 00:00:00+05:30,25430.449219,25430.500000,25292.449219,25356.500000,250800,0.0,0.0
2024-09-16 00:00:00+05:30,25406.650391,25445.699219,25336.199219,25383.750000,168700,0.0,0.0
2024-09-17 00:00:00+05:30,25416.900391,25441.650391,25352.250000,25418.550781,216000,0.0,0.0
2024-09-18 00:00:00+05:30,25402.400391,25482.199219,25285.550781,25377.550781,215700,0.0,0.0
2024-09-19 00:00:00+05:30,25487.050781,25611.949219,25376.050781,25415.800781,314500,0.0,0.0
2024-09-20 00:00:00+05:30,25525.949219,25849.250000,25426.599609,25790.949219,533100,0.0,0.0
2024-09-23 00:00:00+05:30,25872.550781,25956.000000,25847.349609,25939.050781,209200,0.0,0.0
2024-09-24 00:00:00+05:30,25921.449219,26011.550781,25886.849609,25940.400391,384100,0.0,0.0
2024-09-25 00:00:00+05:30,25899.449219,26032.800781,25871.349609,26004.150391,278500,0.0,0.0
2024-09-26 00:00:00+05:30,26005.400391,26250.900391,25998.400391,26216.050781,370900,0.0,0.0
2024-09-27 00:00:00+05:30,26248.250000,26277.349609,26151.400391,26178.949219,490300,0.0,0.0
2024-09-30 00:00:00+05:30,26061.300781,26134.699219,25794.099609,25810.849609,343100,0.0,0.0
2024-10-01 00:00:00+05:30,25788.449219,25907.599609,25739.199219,25796.900391,247400,0.0,0.0
2024-10-03 00:00:00+05:30,25452.849609,25639.449219,25230.300781,25250.099609,423400,0.0,0.0
2024-10-04 00:00:00+05:30,25181.900391,25485.050781,24966.800781,25014.599609,374900,0.0,0.0
2024-10-07 00:00:00+05:30,25084.099609,25143.000000,24694.349609,24795.750000,374300,0.0,0.0
2024-10-08 00:00:00+05:30,24832.199219,25044.000000,24756.800781,25013.150391,333200,0.0,0.0
2024-10-09 00:00:00+05:30,25065.800781,25234.050781,24947.699219,24981.949219,290600,0.0,0.0
2024-10-10 00:00:00+05:30,25067.050781,25134.050781,24979.400391,24998.449219,261400,0.0,0.0
2024-10-11 00:00:00+05:30,24985.300781,25028.650391,24920.050781,24964.250000,210500,0.0,0.0
2024-10-14 00:00:00+05:30,25023.449219,25159.750000,25017.500000,25127.949219,206400,0.0,0.0
2024-10-15 00:00:00+05:30,25186.300781,25212.050781,25008.150391,25057.349609,257200,0.0,0.0
2024-10-16 00:00:00+05:30,25008.550781,25093.400391,24908.449219,24971.300781,226800,0.0,0.0
2024-10-17 00:00:00+05:30,25027.400391,25029.500000,24728.900391,24749.849609,252800,0.0,0.0
2024-10-18 00:00:00+05:30,24664.949219,24886.199219,24567.650391,24854.050781,290900,0.0,0.0
2024-10-21 00:00:00+05:30,24956.150391,24978.300781,24679.599609,24781.099609,242000,0.0,0.0
2024-10-22 00:00:00+05:30,24798.650391,24882.000000,24445.800781,24472.099609,279500,0.0,0.0
2024-10-23 00:00:00+05:30,24378.150391,24604.250000,24378.099609,24435.500000,284600,0.0,0.0
2024-10-24 00:00:00+05:30,24412.699219,24480.650391,24341.199219,24399.400391,216700,0.0,0.0
2024-10-25 00:00:00+05:30,24418.050781,24440.250000,24073.900391,24180.800781,372600,0.0,0.0
2024-10-28 00:00:00+05:30,24251.099609,24492.599609,24134.900391,24339.150391,278600,0.0,0.0
2024-10-29 00:00:00+05:30,24328.849609,24484.500000,24140.849609,24466.849609,332000,0.0,0.0
2024-10-30 00:00:00+05:30,24371.449219,24498.199219,24307.300781,24340.849609,285200,0.0,0.0
2024-10-31 00:00:00+05:30,24349.849609,24372.449219,24172.599609,24205.349609,287000,0.0,0.0
2024-11-01 00:00:00+05:30,24302.750000,24368.250000,24280.199219,24304.349609,38800,0.0,0.0
2024-11-04 00:00:00+05:30,24315.750000,24316.750000,23816.150391,23995.349609,285500,0.0,0.0
2024-11-05 00:00:00+05:30,23916.500000,24229.050781,23842.750000,24213.300781,289500,0.0,0.0
2024-11-06 00:00:00+05:30,24308.750000,24537.599609,24204.050781,24484.050781,351100,0.0,0.0
2024-11-07 00:00:00+05:30,24489.599609,24503.349609,24179.050781,24199.349609,322200,0.0,0.0
2024-11-08 00:00:00+05:30,24207.699219,24276.150391,24066.650391,24148.199219,298700,0.0,0.0
2024-11-11 00:00:00+05:30,24087.250000,24336.800781,24004.599609,24141.300781,273400,0.0,0.0
2024-11-12 00:00:00+05:30,24225.800781,24242.000000,23839.150391,23883.449219,255800,0.0,0.0
2024-11-13 00:00:00+05:30,23822.449219,23873.599609,23509.599609,23559.050781,304600,0.0,0.0
2024-11-14 00:00:00+05:30,23542.150391,23675.900391,23484.150391,23532.699219,257700,0.0,0.0
2024-11-18 00:00:00+05:30,23605.300781,23606.800781,23350.400391,23453.800781,263300,0.0,0.0
2024-11-19 00:00:00+05:30,23529.550781,23780.650391,23464.800781,23518.500000,297500,0.0,0.0
2024-11-21 00:00:00+05:30,23488.449219,23507.300781,23263.150391,23349.900391,420300,0.0,0.0
2024-11-22 00:00:00+05:30,23411.800781,23956.099609,23359.000000,23907.250000,367600,0.0,0.0
2024-11-25 00:00:00+05:30,24253.550781,24351.550781,24135.449219,24221.900391,687200,0.0,0.0
2024-11-26 00:00:00+05:30,24343.300781,24343.300781,24125.400391,24194.500000,230700,0.0,0.0
2024-11-27 00:00:00+05:30,24204.800781,24354.550781,24145.650391,24274.900391,295000,0.0,0.0
2024-11-28 00:00:00+05:30,24274.150391,24345.750000,23873.349609,23914.150391,366700,0.0,0.0
2024-11-29 00:00:00+05:30,23927.150391,24188.449219,23927.150391,24131.099609,282100,0.0,0.0
2024-12-02 00:00:00+05:30,24140.849609,24301.699219,24008.650391,24276.050781,220400,0.0,0.0
2024-12-03 00:00:00+05:30,24367.500000,24481.349609,24280.000000,24457.150391,339500,0.0,0.0
2024-12-04 00:00:00+05:30,24488.750000,24573.199219,24366.300781,24467.449219,348000,0.0,0.0
2024-12-05 00:00:00+05:30,24539.150391,24857.750000,24295.550781,24708.400391,361500,0.0,0.0
2024-12-06 00:00:00+05:30,24729.449219,24751.050781,24620.500000,24677.800781,226700,0.0,0.0
2024-12-09 00:00:00+05:30,24633.900391,24705.000000,24580.050781,24619.000000,248100,0.0,0.0
2024-12-10 00:00:00+05:30,24652.650391,24677.800781,24510.650391,24610.050781,261000,0.0,0.0
2024-12-11 00:00:00+05:30,24620.500000,24691.750000,24583.849609,24641.800781,187300,0.0,0.0
2024-12-12 00:00:00+05:30,24604.449219,24675.250000,24527.949219,24548.699219,266100,0.0,0.0
2024-12-13 00:00:00+05:30,24498.349609,24792.300781,24180.800781,24768.300781,310100,0.0,0.0
2024-12-16 00:00:00+05:30,24753.400391,24781.250000,24601.750000,24668.250000,187600,0.0,0.0
2024-12-17 00:00:00+05:30,24584.800781,24624.099609,24303.449219,24336.000000,264900,0.0,0.0
2024-12-18 00:00:00+05:30,24297.949219,24394.449219,24149.849609,24198.849609,235300,0.0,0.0
2024-12-19 00:00:00+05:30,23877.150391,24004.900391,23870.300781,23951.699219,271100,0.0,0.0
2024-12-20 00:00:00+05:30,23960.699219,24065.800781,23537.349609,23587.500000,442700,0.0,0.0
2024-12-23 00:00:00+05:30,23738.199219,23869.550781,23647.199219,23753.449219,189800,0.0,0.0
2024-12-24 00:00:00+05:30,23769.099609,23867.650391,23685.150391,23727.650391,177700,0.0,0.0
2024-12-26 00:00:00+05:30,23775.800781,23854.500000,23653.599609,23750.199219,177700,0.0,0.0
2024-12-27 00:00:00+05:30,23801.400391,23938.849609,23800.599609,23813.400391,176800,0.0,0.0
2024-12-30 00:00:00+05:30,23796.900391,23915.349609,23599.300781,23644.900391,364900,0.0,0.0
2024-12-31 00:00:00+05:30,23560.599609,23689.849609,23460.449219,23644.800781,193600,0.0,0.0
2025-01-01 00:00:00+05:30,23637.650391,23822.800781,23562.800781,23742.900391,154900,0.0,0.0
2025-01-02 00:00:00+05:30,23783.000000,24226.699219,23751.550781,24188.650391,283200,0.0,0.0
2025-01-03 00:00:00+05:30,24196.400391,24196.449219,23976.000000,24004.750000,312300,0.0,0.0
2025-01-06 00:00:00+05:30,24045.800781,24089.949219,23551.900391,23616.050781,278100,0.0,0.0
2025-01-07 00:00:00+05:30,23679.900391,23795.199219,23637.800781,23707.900391,262300,0.0,0.0
2025-01-08 00:00:00+05:30,23746.650391,23751.849609,23496.150391,23688.949219,266400,0.0,0.0
2025-01-09 00:00:00+05:30,23674.750000,23689.500000,23503.050781,23526.500000,269200,0.0,0.0
2025-01-10 00:00:00+05:30,23551.900391,23596.599609,23344.349609,23431.500000,261000,0.0,0.0
2025-01-13 00:00:00+05:30,23195.400391,23340.949219,23047.250000,23085.949219,316500,0.0,0.0
2025-01-14 00:00:00+05:30,23165.900391,23264.949219,23134.150391,23176.050781,311200,0.0,0.0
2025-01-15 00:00:00+05:30,23250.449219,23293.650391,23146.449219,23213.199219,228000,0.0,0.0
2025-01-16 00:00:00+05:30,23377.250000,23391.650391,23272.050781,23311.800781,299400,0.0,0.0
2025-01-17 00:00:00+05:30,23277.099609,23292.099609,23100.349609,23203.199219,272900,0.0,0.0
2025-01-20 00:00:00+05:30,23290.400391,23391.099609,23170.650391,23344.750000,301500,0.0,0.0
2025-01-21 00:00:00+05:30,23421.650391,23426.300781,22976.849609,23024.650391,312900,0.0,0.0
2025-01-22 00:00:00+05:30,23099.150391,23169.550781,22981.300781,23155.349609,276000,0.0,0.0
2025-01-23 00:00:00+05:30,23128.300781,23270.800781,23090.650391,23205.349609,275600,0.0,0.0
2025-01-24 00:00:00+05:30,23183.900391,23347.300781,23050.000000,23092.199219,264300,0.0,0.0
2025-01-27 00:00:00+05:30,22940.150391,23007.449219,22786.900391,22829.150391,257400,0.0,0.0
2025-01-28 00:00:00+05:30,22960.449219,23137.949219,22857.650391,22957.250000,361900,0.0,0.0
2025-01-29 00:00:00+05:30,23026.750000,23183.349609,22976.500000,23163.099609,226300,0.0,0.0
2025-01-30 00:00:00+05:30,23169.500000,23322.050781,23139.199219,23249.500000,361900,0.0,0.0
2025-01-31 00:00:00+05:30,23296.750000,23546.800781,23277.400391,23508.400391,304900,0.0,0.0
2025-02-03 00:00:00+05:30,23319.349609,23381.599609,23222.000000,23361.050781,329700,0.0,0.0
2025-02-04 00:00:00+05:30,23509.900391,23762.750000,23423.150391,23739.250000,376700,0.0,0.0
2025-02-05 00:00:00+05:30,23801.750000,23807.300781,23680.449219,23696.300781,267000,0.0,0.0
2025-02-06 00:00:00+05:30,23761.949219,23773.550781,23556.250000,23603.349609,307000,0.0,0.0
2025-02-07 00:00:00+05:30,23649.500000,23694.500000,23443.199219,23559.949219,368100,0.0,0.0
2025-02-10 00:00:00+05:30,23543.800781,23568.599609,23316.300781,23381.599609,234200,0.0,0.0
2025-02-11 00:00:00+05:30,23383.550781,23390.050781,22986.650391,23071.800781,268000,0.0,0.0
2025-02-12 00:00:00+05:30,23050.800781,23144.699219,22798.349609,23045.250000,279700,0.0,0.0
2025-02-13 00:00:00+05:30,23055.750000,23235.500000,22992.199219,23031.400391,265700,0.0,0.0
2025-02-14 00:00:00+05:30,23096.449219,23133.699219,22774.849609,22929.250000,254500,0.0,0.0
2025-02-17 00:00:00+05:30,22809.900391,22974.199219,22725.449219,22959.500000,207400,0.0,0.0
2025-02-18 00:00:00+05:30,22963.650391,22992.500000,22801.500000,22945.300781,210600,0.0,0.0
2025-02-19 00:00:00+05:30,22847.250000,23049.949219,22814.849609,22932.900391,207000,0.0,0.0
2025-02-20 00:00:00+05:30,22821.099609,22923.849609,22812.750000,22913.150391,0,0.0,0.0

In [14]:
stock_returns = stock_hist['Close'].pct_change().dropna()

In [37]:
stock_returns

Date
2024-04-23 00:00:00+02:00    0.018320
2024-04-24 00:00:00+02:00   -0.000878
2024-04-25 00:00:00+02:00   -0.005709
2024-04-26 00:00:00+02:00    0.019876
2024-04-29 00:00:00+02:00    0.006063
                               ...
2024-10-14 00:00:00+02:00    0.013699
2024-10-15 00:00:00+02:00    0.012247
2024-10-16 00:00:00+02:00   -0.062578
2024-10-17 00:00:00+02:00    0.002670
2024-10-18 00:00:00+02:00    0.011540
Name: Close, Length: 128, dtype: float64

In [15]:
benchmark_returns = benchmark_hist['Close'].pct_change().dropna()

In [16]:
benchmark_returns

Date
2024-08-27 00:00:00+05:30    0.000286
2024-08-28 00:00:00+05:30    0.001383
2024-08-29 00:00:00+05:30    0.003976
2024-08-30 00:00:00+05:30    0.003338
2024-09-02 00:00:00+05:30    0.001696
2024-09-03 00:00:00+05:30    0.000046
2024-09-04 00:00:00+05:30   -0.003210
2024-09-05 00:00:00+05:30   -0.002127
2024-09-06 00:00:00+05:30   -0.011650
2024-09-09 00:00:00+05:30    0.003390
2024-09-10 00:00:00+05:30    0.004199
2024-09-11 00:00:00+05:30   -0.004898
2024-09-12 00:00:00+05:30    0.018880
2024-09-13 00:00:00+05:30   -0.001276
2024-09-16 00:00:00+05:30    0.001075
2024-09-17 00:00:00+05:30    0.001371
2024-09-18 00:00:00+05:30   -0.001613
2024-09-19 00:00:00+05:30    0.001507
2024-09-20 00:00:00+05:30    0.014760
2024-09-23 00:00:00+05:30    0.005742
2024-09-24 00:00:00+05:30    0.000052
2024-09-25 00:00:00+05:30    0.002458
2024-09-26 00:00:00+05:30    0.008149
2024-09-27 00:00:00+05:30   -0.001415
2024-09-30 00:00:00+05:30   -0.014061
2024-10-01 00:00:00+05:30   -0.000540
2024-10-03 00:00:00+05:30   -0.021196
2024-10-04 00:00:00+05:30   -0.009327
2024-10-07 00:00:00+05:30   -0.008749
2024-10-08 00:00:00+05:30    0.008768
2024-10-09 00:00:00+05:30   -0.001247
2024-10-10 00:00:00+05:30    0.000660
2024-10-11 00:00:00+05:30   -0.001368
2024-10-14 00:00:00+05:30    0.006557
2024-10-15 00:00:00+05:30   -0.002810
2024-10-16 00:00:00+05:30   -0.003434
2024-10-17 00:00:00+05:30   -0.008868
2024-10-18 00:00:00+05:30    0.004210
2024-10-21 00:00:00+05:30   -0.002935
2024-10-22 00:00:00+05:30   -0.012469
2024-10-23 00:00:00+05:30   -0.001496
2024-10-24 00:00:00+05:30   -0.001477
2024-10-25 00:00:00+05:30   -0.008959
2024-10-28 00:00:00+05:30    0.006549
2024-10-29 00:00:00+05:30    0.005247
2024-10-30 00:00:00+05:30   -0.005150
2024-10-31 00:00:00+05:30   -0.005567
2024-11-01 00:00:00+05:30    0.004090
2024-11-04 00:00:00+05:30   -0.012714
2024-11-05 00:00:00+05:30    0.009083
2024-11-06 00:00:00+05:30    0.011182
2024-11-07 00:00:00+05:30   -0.011628
2024-11-08 00:00:00+05:30   -0.002114
2024-11-11 00:00:00+05:30   -0.000286
2024-11-12 00:00:00+05:30   -0.010681
2024-11-13 00:00:00+05:30   -0.013583
2024-11-14 00:00:00+05:30   -0.001119
2024-11-18 00:00:00+05:30   -0.003353
2024-11-19 00:00:00+05:30    0.002759
2024-11-21 00:00:00+05:30   -0.007169
2024-11-22 00:00:00+05:30    0.023869
2024-11-25 00:00:00+05:30    0.013161
2024-11-26 00:00:00+05:30   -0.001131
2024-11-27 00:00:00+05:30    0.003323
2024-11-28 00:00:00+05:30   -0.014861
2024-11-29 00:00:00+05:30    0.009072
2024-12-02 00:00:00+05:30    0.006007
2024-12-03 00:00:00+05:30    0.007460
2024-12-04 00:00:00+05:30    0.000421
2024-12-05 00:00:00+05:30    0.009848
2024-12-06 00:00:00+05:30   -0.001238
2024-12-09 00:00:00+05:30   -0.002383
2024-12-10 00:00:00+05:30   -0.000364
2024-12-11 00:00:00+05:30    0.001290
2024-12-12 00:00:00+05:30   -0.003778
2024-12-13 00:00:00+05:30    0.008946
2024-12-16 00:00:00+05:30   -0.004039
2024-12-17 00:00:00+05:30   -0.013469
2024-12-18 00:00:00+05:30   -0.005636
2024-12-19 00:00:00+05:30   -0.010213
2024-12-20 00:00:00+05:30   -0.015206
2024-12-23 00:00:00+05:30    0.007035
2024-12-24 00:00:00+05:30   -0.001086
2024-12-26 00:00:00+05:30    0.000950
2024-12-27 00:00:00+05:30    0.002661
2024-12-30 00:00:00+05:30   -0.007076
2024-12-31 00:00:00+05:30   -0.000004
2025-01-01 00:00:00+05:30    0.004149
2025-01-02 00:00:00+05:30    0.018774
2025-01-03 00:00:00+05:30   -0.007603
2025-01-06 00:00:00+05:30   -0.016193
2025-01-07 00:00:00+05:30    0.003889
2025-01-08 00:00:00+05:30   -0.000799
2025-01-09 00:00:00+05:30   -0.006858
2025-01-10 00:00:00+05:30   -0.004038
2025-01-13 00:00:00+05:30   -0.014747
2025-01-14 00:00:00+05:30    0.003903
2025-01-15 00:00:00+05:30    0.001603
2025-01-16 00:00:00+05:30    0.004248
2025-01-17 00:00:00+05:30   -0.004659
2025-01-20 00:00:00+05:30    0.006100
2025-01-21 00:00:00+05:30   -0.013712
2025-01-22 00:00:00+05:30    0.005676
2025-01-23 00:00:00+05:30    0.002159
2025-01-24 00:00:00+05:30   -0.004876
2025-01-27 00:00:00+05:30   -0.011391
2025-01-28 00:00:00+05:30    0.005611
2025-01-29 00:00:00+05:30    0.008967
2025-01-30 00:00:00+05:30    0.003730
2025-01-31 00:00:00+05:30    0.011136
2025-02-03 00:00:00+05:30   -0.006268
2025-02-04 00:00:00+05:30    0.016189
2025-02-05 00:00:00+05:30   -0.001809
2025-02-06 00:00:00+05:30   -0.003923
2025-02-07 00:00:00+05:30   -0.001839
2025-02-10 00:00:00+05:30   -0.007570
2025-02-11 00:00:00+05:30   -0.013250
2025-02-12 00:00:00+05:30   -0.001151
2025-02-13 00:00:00+05:30   -0.000601
2025-02-14 00:00:00+05:30   -0.004435
2025-02-17 00:00:00+05:30    0.001319
2025-02-18 00:00:00+05:30   -0.000618
2025-02-19 00:00:00+05:30   -0.000540
2025-02-20 00:00:00+05:30   -0.000861
Name: Close, dtype: float64

In [17]:
stock_returns, benchmark_returns = stock_returns.align(benchmark_returns, join='inner')

In [42]:
stock_returns

Date
2024-04-23 00:00:00+02:00    0.018320
2024-04-24 00:00:00+02:00   -0.000878
2024-04-25 00:00:00+02:00   -0.005709
2024-04-26 00:00:00+02:00    0.019876
2024-04-29 00:00:00+02:00    0.006063
                               ...
2024-10-14 00:00:00+02:00    0.013699
2024-10-15 00:00:00+02:00    0.012247
2024-10-16 00:00:00+02:00   -0.062578
2024-10-17 00:00:00+02:00    0.002670
2024-10-18 00:00:00+02:00    0.011540
Name: Close, Length: 128, dtype: float64

In [19]:
stock_returns.std()

0.014758513954413993

In [43]:
benchmark_returns

Date
2024-04-23 00:00:00+02:00    0.015500
2024-04-24 00:00:00+02:00   -0.002699
2024-04-25 00:00:00+02:00   -0.009477
2024-04-26 00:00:00+02:00    0.013603
2024-04-29 00:00:00+02:00   -0.002351
                               ...
2024-10-14 00:00:00+02:00    0.006940
2024-10-15 00:00:00+02:00   -0.001133
2024-10-16 00:00:00+02:00   -0.002739
2024-10-17 00:00:00+02:00    0.007749
2024-10-18 00:00:00+02:00    0.003778
Name: Close, Length: 128, dtype: float64

In [20]:
stock.income_stmt.index

Index(['Tax Effect Of Unusual Items', 'Tax Rate For Calcs',
       'Total Unusual Items', 'Total Unusual Items Excluding Goodwill',
       'Net Income From Continuing Operation Net Minority Interest',
       'Reconciled Depreciation', 'Net Interest Income', 'Interest Expense',
       'Interest Income', 'Normalized Income',
       'Net Income From Continuing And Discontinued Operation',
       'Diluted Average Shares', 'Basic Average Shares', 'Diluted EPS',
       'Basic EPS', 'Diluted NI Availto Com Stockholders',
       'Net Income Common Stockholders', 'Net Income', 'Minority Interests',
       'Net Income Including Noncontrolling Interests',
       'Net Income Extraordinary', 'Net Income Continuous Operations',
       'Tax Provision', 'Pretax Income', 'Special Income Charges',
       'Other Special Charges', 'Gain On Sale Of Security',
       'Operating Expense', 'Other Operating Expenses',
       'Depreciation And Amortization In Income Statement',
       'Depreciation Income Statement', 'Selling General And Administration',
       'Selling And Marketing Expense', 'General And Administrative Expense',
       'Insurance And Claims', 'Rent And Landing Fees', 'Total Revenue',
       'Operating Revenue'],
      dtype='object')

In [21]:
stock.eps_trend['analyst_price_targets']

period
0q     18.30000
+1q    18.10000
0y     78.55043
+1y    83.28842
Name: 90daysAgo, dtype: float64

In [22]:
stock.analyst_price_targets['current']

729.7

In [45]:
volatility = stock_returns.std() * np.sqrt(252)

In [46]:
volatility

0.2521462088557039

In [47]:
pe_ratio = stock.info.get('trailingPE', None)

In [48]:
pe_ratio

211.01851

In [20]:
stock = yf.Ticker("SBIN.NS")

In [18]:
stock.income_stmt

,2024-03-31,2023-03-31,2022-03-31,2021-03-31
Tax Effect Of Unusual Items,-63819520.14808,-72542383.86833,-44137774.290276,-73582175.029619
Tax Rate For Calcs,0.253198,0.249874,0.269056,0.259674
Total Unusual Items,-252054000.0,-290316000.0,-164047000.0,-283364000.0
Total Unusual Items Excluding Goodwill,-252054000.0,-290316000.0,-164047000.0,-283364000.0
Net Income From Continuing Operation Net Minority Interest,670846661000.0,556481728000.0,353738798000.0,224054576000.0
Reconciled Depreciation,38491245000.0,36955986000.0,36912700000.0,37110636000.0
Net Interest Income,1794524642000.0,1608637634000.0,1337783419000.0,1221053096000.0
Interest Expense,2597360481000.0,1899808167000.0,1561943441000.0,1560101671000.0
Interest Income,4391885123000.0,3508445801000.0,2899726860000.0,2781154767000.0
Normalized Income,671034895479.851929,556699501616.131714,353858707225.709717,224264357824.970367
Net Income From Continuing And Discontinued Operation,670846661000.0,556481728000.0,353738798000.0,224054576000.0
Diluted Average Shares,8924611934.0,8924611707.0,8924611534.0,8924611534.0
Basic Average Shares,8924611934.0,8924611707.0,8924611534.0,8924611534.0
Diluted EPS,75.17,62.35,39.64,25.11
Basic EPS,75.17,62.35,39.64,25.11
Diluted NI Availto Com Stockholders,670846661000.0,556481728000.0,353738798000.0,224054576000.0
Net Income Common Stockholders,670846661000.0,556481728000.0,353738798000.0,224054576000.0
Net Income,670846661000.0,556481728000.0,353738798000.0,224054576000.0
Minority Interests,-24587491000.0,-21017092000.0,-18093049000.0,-14823573000.0
Net Income Including Noncontrolling Interests,695434219000.0,577498807000.0,371831831000.0,238878136000.0
Net Income Extraordinary,0.0,0.0,0.0,0.0
Net Income Continuous Operations,695434219000.0,577498807000.0,371831831000.0,238878136000.0
Tax Provision,231017800000.0,188401300000.0,133824600000.0,85162500000.0
Pretax Income,912400476000.0,753985586000.0,497386298000.0,327959681000.0
Special Income Charges,-252054000.0,-290316000.0,-164047000.0,-283364000.0
Other Special Charges,252054000.0,290316000.0,164047000.0,283364000.0
Gain On Sale Of Security,137828728000.0,2354761000.0,59299092000.0,74992992000.0
Operating Expense,2288145880000.0,1861696085000.0,1741951087000.0,1588737760000.0
Other Operating Expenses,282213147000.0,266484524000.0,254053816000.0,294457786000.0
Depreciation And Amortization In Income Statement,38491245000.0,36955986000.0,36912700000.0,37110636000.0
Depreciation Income Statement,38491245000.0,36955986000.0,36912700000.0,37110636000.0
Selling General And Administration,44226864000.0,42205328000.0,34260654000.0,31458007000.0
Selling And Marketing Expense,34490995000.0,34192691000.0,26939263000.0,24586307000.0
General And Administrative Expense,9735869000.0,8012637000.0,7321391000.0,6871700000.0
Insurance And Claims,1020886893000.0,835678715000.0,745067008000.0,626699061000.0
Rent And Landing Fees,65461669000.0,61030583000.0,57077368000.0,55571372000.0
Total Revenue,3236135037000.0,2703369068000.0,2360910738000.0,2143316771000.0
Operating Revenue,3236135037000.0,2703369068000.0,2360910738000.0,2143316771000.0

In [15]:
stock.income_stmt.loc['EBITDA']

KeyError: 'EBITDA'

In [25]:
# Define the dictionary
data = {'a': 1, 'b': 2, 'c': 3}

# Create the f-string by looping through the dictionary
fstring = ", ".join([f"{key}: {value}\n" for key, value in data.items()])

# Print the result
print(f"fstring = f'''{fstring}'''")

fstring = f'''a: 1
, b: 2
, c: 3
'''

In [10]:
stock.balance_sheet

,2024-03-31,2023-03-31,2022-03-31,2021-03-31
Treasury Shares Number,0.0,NaN,NaN,NaN
Ordinary Shares Number,8924611934.0,8924611934.0,8924611534.0,8924611534.0
Share Issued,8924611934.0,8924611934.0,8924611534.0,8924611534.0
Net Debt,3130372000000.0,2028400400000.0,502546600000.0,860891700000.0
Total Debt,5565032351000.0,5220926306000.0,4576896083000.0,4265687251000.0
Tangible Book Value,4135332107000.0,3573929554000.0,3040380204000.0,2740115659000.0
Invested Capital,9714424066000.0,8810239487000.0,7632776534000.0,7021302851000.0
Net Tangible Assets,4135332107000.0,3573929554000.0,3040380204000.0,2740115659000.0
Common Stock Equity,4149391715000.0,3589313181000.0,3055880451000.0,2755615600000.0
Total Capitalization,9714424066000.0,8810239487000.0,7632776534000.0,7021302851000.0
Total Equity Gross Minority Interest,4305571339000.0,3717679375000.0,3167954679000.0,2851874766000.0
Minority Interest,156179624000.0,128366194000.0,112074228000.0,96259166000.0
Stockholders Equity,4149391715000.0,3589313181000.0,3055880451000.0,2755615600000.0
Fixed Assets Revaluation Reserve,709722091000.0,639825804000.0,233778671000.0,235773478000.0
Retained Earnings,720191793000.0,419233028000.0,203943505000.0,80965411000.0
Additional Paid In Capital,791154768000.0,791154768000.0,791154705000.0,791154705000.0
Capital Stock,8924612000.0,8924612000.0,8924612000.0,8924612000.0
Common Stock,8924612000.0,8924612000.0,8924612000.0,8924612000.0
Total Liabilities Net Minority Interest,63032216658000.0,55826503795000.0,50440880615000.0,45604310699000.0
Long Term Debt And Capital Lease Obligation,5565032351000.0,5220926306000.0,4576896083000.0,4265687251000.0
Payables,328616148000.0,274950255000.0,179906159000.0,153091571000.0
Accounts Payable,328616148000.0,274950255000.0,179906159000.0,153091571000.0
Total Assets,67337787997000.0,59544183170000.0,53608835294000.0,48456185465000.0
Investments And Advances,21105482259000.0,19131078564000.0,17764898988000.0,15951002664000.0
Investmentin Financial Assets,20928726486000.0,18969186428000.0,17617277440000.0,15817456287000.0
Available For Sale Securities,929631400000.0,797507703000.0,808623409000.0,694052892000.0
Long Term Equity Investment,176755773000.0,161892136000.0,147621548000.0,133546377000.0
Investmentsin Associatesat Cost,1770173000.0,1760239000.0,1588087000.0,1456273000.0
Investmentsin Subsidiariesat Cost,174985600000.0,160131897000.0,146033461000.0,132090104000.0
Goodwill And Other Intangible Assets,14059608000.0,15383627000.0,15500247000.0,15499941000.0
Goodwill,14059608000.0,15383627000.0,15500247000.0,15499941000.0
Net PPE,447081773000.0,444073810000.0,395100305000.0,401667882000.0
Accumulated Depreciation,-394837325000.0,-366053269000.0,-337072290000.0,-307116065000.0
Gross PPE,841919098000.0,810127079000.0,732172595000.0,708783947000.0
Construction In Progress,5708864000.0,3835664000.0,2805323000.0,4681814000.0
Other Properties,475971142000.0,446831650000.0,416001185000.0,392801790000.0
Properties,360239092000.0,359459765000.0,313366087000.0,311300343000.0
Prepaid Assets,239897760000.0,168897362000.0,226501252000.0,264353867000.0
Receivables,2710336087000.0,2264466803000.0,2055968294000.0,1290346894000.0
Cash And Cash Equivalents,5975677770000.0,5369031044000.0,5945234169000.0,5318004905000.0
Cash Equivalents,429233574000.0,113481426000.0,89620475000.0,97355329000.0
Cash Financial,185896478000.0,216284177000.0,219672206000.0,236913243000.0
Cash Cash Equivalents And Federal Funds Sold,5975677770000.0,5369031044000.0,5945234169000.0,5318004905000.0

In [ ]:
stock.balance_sheet.iloc[79]

2024-03-31    19503800000.0
2023-03-31    17909200000.0
2022-03-31    17959000000.0
2021-03-31    12795900000.0
2020-03-31              NaN
Name: Gross Accounts Receivable, dtype: object

In [12]:
Total_Assets = stock.balance_sheet.loc['Total Assets']
Total_Assets

2024-03-31    67337787997000.0
2023-03-31    59544183170000.0
2022-03-31    53608835294000.0
2021-03-31    48456185465000.0
Name: Total Assets, dtype: object

In [23]:
stock.cashflow

,2024-03-31,2023-03-31,2022-03-31,2021-03-31,2020-03-31
Free Cash Flow,-1230700000.0,359600000.0,2736500000.0,5573300000.0,NaN
Repayment Of Debt,-4971600000.0,-7587800000.0,-4709400000.0,-19904100000.0,NaN
Issuance Of Debt,10375900000.0,14186400000.0,5331500000.0,13048400000.0,NaN
Issuance Of Capital Stock,0.0,0.0,2000000.0,7500000000.0,NaN
Capital Expenditure,-22169300000.0,-28657500000.0,-18320700000.0,-12143500000.0,NaN
End Cash Position,3993300000.0,6079800000.0,4504800000.0,1382900000.0,NaN
Beginning Cash Position,6079800000.0,4504800000.0,1382900000.0,1164400000.0,NaN
Effect Of Exchange Rate Changes,-34800000.0,-23800000.0,14900000.0,9600000.0,NaN
Changes In Cash,-2051700000.0,1598800000.0,3107000000.0,208900000.0,NaN
Financing Cash Flow,-717000000.0,2195800000.0,-2072800000.0,-2511100000.0,NaN
Net Other Financing Charges,NaN,NaN,NaN,-3400000.0,-165400000.0
Interest Paid Cff,-3612400000.0,-1944900000.0,-1172500000.0,-1573600000.0,NaN
Cash Dividends Paid,-2137100000.0,-2133200000.0,-2117400000.0,-1407800000.0,NaN
Common Stock Dividend Paid,-2137100000.0,-2133200000.0,NaN,NaN,-803200000.0
Net Common Stock Issuance,0.0,0.0,2000000.0,7500000000.0,NaN
Common Stock Issuance,0.0,0.0,2000000.0,7500000000.0,NaN
Net Issuance Payments Of Debt,5404300000.0,6598600000.0,1471900000.0,-6707900000.0,NaN
Net Short Term Debt Issuance,349200000.0,4862200000.0,849800000.0,147800000.0,NaN
Short Term Debt Issuance,349200000.0,4862200000.0,NaN,NaN,NaN
Net Long Term Debt Issuance,5055100000.0,1736400000.0,622100000.0,-6855700000.0,NaN
Long Term Debt Payments,-4971600000.0,-7587800000.0,-4709400000.0,-19904100000.0,NaN
Long Term Debt Issuance,10026700000.0,9324200000.0,5331500000.0,13048400000.0,NaN
Investing Cash Flow,-22273300000.0,-29614100000.0,-15877400000.0,-14996800000.0,NaN
Net Other Investing Changes,-282800000.0,274200000.0,1049000000.0,-1065100000.0,NaN
Interest Received Cfi,265100000.0,272500000.0,316000000.0,900000.0,NaN
Net Investment Purchase And Sale,-238200000.0,-1642100000.0,1028400000.0,-1885700000.0,NaN
Sale Of Investment,1114500000.0,0.0,1028400000.0,NaN,NaN
Purchase Of Investment,-1352700000.0,-1642100000.0,NaN,-1887200000.0,-926800000.0
Net Business Purchase And Sale,NaN,0.0,-99600000.0,0.0,3157700000.0
Sale Of Business,NaN,NaN,NaN,0.0,3157700000.0
Purchase Of Business,NaN,0.0,-99600000.0,0.0,NaN
Net PPE Purchase And Sale,-22017400000.0,-28518700000.0,-18171200000.0,-12046900000.0,NaN
Sale Of PPE,151900000.0,138800000.0,149500000.0,96600000.0,NaN
Purchase Of PPE,-22169300000.0,-28657500000.0,-18320700000.0,-12143500000.0,NaN
Capital Expenditure Reported,-22169300000.0,-28381800000.0,NaN,NaN,-13891600000.0
Operating Cash Flow,20938600000.0,29017100000.0,21057200000.0,17716800000.0,NaN
Taxes Refund Paid,-3825600000.0,-5077100000.0,-4016000000.0,-2553100000.0,NaN
Change In Working Capital,-1144700000.0,-603700000.0,-6644600000.0,-1236000000.0,NaN
Change In Other Current Liabilities,824600000.0,1153600000.0,219200000.0,164400000.0,NaN
Change In Other Current Assets,567800000.0,-1416700000.0,-249600000.0,317400000.0,NaN
Change In Payable,-142400000.0,1221000000.0,5101100000.0,4802300000.0,NaN
Change In Inventory,-741800000.0,-1307000000.0,-6656700000.0,-2598300000.0,NaN
Change In Receivables,-1759900000.0,-351700000.0,-5125400000.0,-3996400000.0,NaN
Other Non Cash Items,2555600000.0,1550800000.0,901700000.0,1236100000.0,NaN
Stock Based Compensation,85400000.0,84100000.0,111100000.0,9700000.0,NaN
Provisionand Write Offof Assets,-125400000.0,-274400000.0,-27100000.0,-119900000.0,NaN
Deferred Tax,1300000.0,700000.0,800000.0,1500000.0,NaN
Depreciation And Amortization,6726200000.0,5753200000.0,5172300000.0,4530800000.0,NaN
Depreciation,6726200000.0,5753200000.0,5172300000.0,4530800000.0,NaN
Gain Loss On Investment Securities,-228800000.0,-91000000.0,-70600000.0,-254500000.0,NaN
Net Foreign Currency Exchange Gain Loss,-142500000.0,-569700000.0,-394400000.0,-90500000.0,NaN
Gain Loss On Sale Of PPE,-47400000.0,-60000000.0,159000000.0,-25900000.0,NaN
Gain Loss On Sale Of Business,NaN,NaN,NaN,0.0,-2337400000.0
Net Income From Continuing Operations,16922200000.0,28239900000.0,25855500000.0,16099200000.0,NaN

In [ ]:
# stock.balance_sheet.iloc[42]

KeyError: 'Repayment Of Debt'

In [24]:
stock.cashflow.iloc[40]

2024-03-31    -142400000.0
2023-03-31    1221000000.0
2022-03-31    5101100000.0
2021-03-31    4802300000.0
2020-03-31             NaN
Name: Change In Payable, dtype: object

In [40]:
tech = yf.Sector(stock.info.get('sectorKey'))
software = yf.Industry(stock.info.get('industryKey'))
print(tech, software)

yfinance.Sector object <basic-materials> yfinance.Industry object <specialty-chemicals>

In [43]:
tech_ticker = tech.ticker
tech_ticker.info

{'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1670870.0,
 'regularMarketPreviousClose': 1670870.0,
 'fiftyTwoWeekLow': 1444676.8,
 'fiftyTwoWeekHigh': 1791916.2,
 'fiftyDayAverage': 1722606.4,
 'twoHundredDayAverage': 1666850.5,
 'currency': 'USD',
 'exchange': 'YHD',
 'quoteType': 'INDEX',
 'symbol': '^YH101',
 'underlyingSymbol': '^YH101',
 'shortName': '^YH101,^YH101,',
 'longName': 'Basic Materials (Sector)',
 'firstTradeDateEpochUtc': 1483367400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': '9fe72762-6c2d-39dc-aeca-a3b2d1950883',
 'messageBoardId': 'finmb_INDEXYH101',
 'gmtOffSetMilliseconds': -18000000,
 'trailingPegRatio': None}

In [ ]:
stock.S

In [42]:
software_ticker = software.ticker
software_ticker.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-10-16 00:00:00-04:00,742919.1250,742919.1250,742919.1250,742919.1250,0,0.0,0.0
2024-10-17 00:00:00-04:00,742638.0625,742638.0625,742638.0625,742638.0625,0,0.0,0.0
2024-10-18 00:00:00-04:00,743465.6875,743465.6875,743465.6875,743465.6875,0,0.0,0.0
2024-10-21 00:00:00-04:00,736188.2500,736188.2500,736188.2500,736188.2500,0,0.0,0.0
2024-10-22 00:00:00-04:00,728332.6250,728332.6250,728332.6250,728332.6250,0,0.0,0.0
2024-10-23 00:00:00-04:00,724959.6875,724959.6875,724959.6875,724959.6875,0,0.0,0.0
2024-10-24 00:00:00-04:00,724959.6875,724959.6875,724959.6875,724959.6875,0,0.0,0.0
2024-10-25 00:00:00-04:00,724959.6875,724959.6875,724959.6875,724959.6875,0,0.0,0.0
2024-10-28 00:00:00-04:00,721928.3750,721928.3750,721928.3750,721928.3750,0,0.0,0.0
2024-10-29 00:00:00-04:00,717605.8125,717605.8125,717605.8125,717605.8125,0,0.0,0.0
2024-10-30 00:00:00-04:00,716586.0625,716586.0625,716586.0625,716586.0625,0,0.0,0.0
2024-10-31 00:00:00-04:00,701380.5625,701380.5625,701380.5625,701380.5625,0,0.0,0.0
2024-11-01 00:00:00-04:00,701074.0625,701074.0625,701074.0625,701074.0625,0,0.0,0.0
2024-11-04 00:00:00-05:00,704938.6875,704938.6875,704938.6875,704938.6875,0,0.0,0.0
2024-11-05 00:00:00-05:00,708170.2500,708170.2500,708170.2500,708170.2500,0,0.0,0.0
2024-11-06 00:00:00-05:00,714606.8750,714606.8750,714606.8750,714606.8750,0,0.0,0.0
2024-11-07 00:00:00-05:00,719319.5000,719319.5000,719319.5000,719319.5000,0,0.0,0.0
2024-11-08 00:00:00-05:00,716029.4375,716029.4375,716029.4375,716029.4375,0,0.0,0.0
2024-11-11 00:00:00-05:00,717057.8125,717057.8125,717057.8125,717057.8125,0,0.0,0.0
2024-11-12 00:00:00-05:00,708302.8750,708302.8750,708302.8750,708302.8750,0,0.0,0.0
2024-11-13 00:00:00-05:00,711794.5625,711794.5625,711794.5625,711794.5625,0,0.0,0.0
2024-11-14 00:00:00-05:00,708917.8125,708917.8125,708917.8125,708917.8125,0,0.0,0.0
2024-11-15 00:00:00-05:00,0.0000,0.0000,0.0000,702044.3750,0,0.0,0.0

In [25]:
stock.sustainability

404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/SRF.NS?modules=esgScores&corsDomain=finance.yahoo.com&formatted=false&symbol=SRF.NS&crumb=R6c4FVT5c23

Empty DataFrame
Columns: []
Index: []

In [26]:
stock.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          7    4     7     7           2
1    -1m          8    6     7     4           2

In [27]:
stock.recommendations_summary

  period  strongBuy  buy  hold  sell  strongSell
0     0m          7    4     7     7           2
1    -1m          8    6     7     4           2

In [28]:
stock.analyst_price_targets

{'current': 2235.2,
 'low': 1500.0,
 'high': 2770.0,
 'mean': 2245.3928,
 'median': 2296.5}

In [30]:
stock.analyst_price_targets['current']

2235.2

In [ ]:
stock.earnings_estimate['']

     numberOfAnalysts       avg       low      high  yearAgoEps  growth
0q                  1  11.34715  11.34715  11.34715     8.55000  0.3272
+1q                 1  21.95413  21.95413  21.95413    14.24000  0.5417
0y                 26  41.01125  31.18704  50.90000    45.06000 -0.0899
+1y                28  60.26213  43.67000  76.90000    41.01125  0.4694

In [31]:
stock.revenue_estimate

,numberOfAnalysts,avg,low,high,yearAgoRevenue,growth
0q,3,34494146670,32983440000,35555000000,30530400000,0.1298
+1q,3,40246018540,37831055630,41759000000,35697400000,0.1274
0y,28,143927395850,135567000000,152647000000,131385200000,0.0955
+1y,29,165823452690,152039000000,179023000000,143927395850,0.1521

In [32]:
stock.earnings_history

            epsEstimate  epsActual  epsDifference  surprisePercent
2023-12-31     11.46881       8.55          -2.92          -0.2545
2024-03-31     14.11410      14.24           0.13           0.0089
2024-06-30      9.92625       8.51          -1.42          -0.1427
2024-09-30      9.80475       6.79          -3.01          -0.3075

In [33]:
stock.eps_trend

      current  7daysAgo  30daysAgo  60daysAgo  90daysAgo
0q   11.34715  16.47459   16.47459   16.47459   16.47459
+1q  21.95413  23.53784   23.53784   23.53784   23.53784
0y   41.01125  51.12378   53.67491   53.67491   53.66330
+1y  60.26213  72.76561   73.55644   73.55644   73.57274

In [67]:
stock.mutualfund_holders

,Date Reported,Holder,pctHeld,Shares,Value
0,2023-12-31,Europacific Growth Fund,0.0235,4233691,779676534
1,2023-10-31,Vanguard International Stock Index-Total Intl ...,0.0124,2240056,374537363
2,2023-12-31,Artisan International Value Fund,0.0101,1815129,334274156
3,2023-12-31,Vanguard Tax Managed Fund-Vanguard Developed M...,0.0075,1343536,247425589
4,2023-12-31,Oakmark International Fund,0.0071,1274300,234675088
5,2023-09-30,Dodge & Cox International Stock Fund,0.0067,1200700,200060634
6,2024-01-31,iShares Core MSCI EAFE ETF,0.0051,921134,162230120
7,2023-11-30,MFS Series Trust X-MFS International Intrinsic...,0.0046,820271,157606869
8,2023-11-30,BNY Mellon International Stock Fd,0.0037,663300,127446462
9,2023-12-31,"New World Fund, Inc.",0.0035,631789,116350262

In [68]:
stock.eps_revisions

     upLast7days  upLast30days downLast7days  downLast30days
0q             4             6          None               0
+1q            4             5          None               0
0y             3            18          None               0
+1y            3            18          None               0

In [5]:
stock.growth_estimates

        stock industry sector index
0q     0.3272     0.05    NaN   NaN
+1q    0.5417     0.12    NaN   NaN
0y    -0.0899    0.021    NaN   NaN
+1y    0.4694    0.122    NaN   NaN
+5y  0.110056      NaN    NaN   NaN
-5y      None     None   None  None
LTG     0.182      NaN    NaN   NaN